include: 
  - project: "libs/gitlab"
    ref: master
    file: "_domain.service.yml"
 
variables:
    absoluteTestDir: "${CI_PROJECT_DIR}/tests/Superbrands.BusinessProcessor.Tests"
    Deploy_Bind_To_Port: 5022
    DockerAppNameLowercase: "businessprocessor"
    restClientDir: "${absoluteSrcDir}/Superbrands.Libs.Restclients.BusinessProcessor"

stages:
    - build
    - test
    - publish
    - deploy
    - integration_tests